-- =============================================================================
-- Phase 4 | 02_dml.sql
-- Loads ~86k synthetic rows from csv_output/*.csv and backfills counters.
-- -----------------------------------------------------------------------------
-- Run AFTER 01_ddl.sql and BEFORE 04_advanced.sql. Triggers must NOT exist yet,
-- otherwise COPY will be slow and may hit constraints out of order.
--
-- Usage (from project root, psql client):
--   \i phase4/01_ddl.sql
--   \i phase4/02_dml.sql
--   \i phase4/04_advanced.sql      -- triggers come AFTER the load
--   \i phase4/03_reports.sql       -- analytical queries (any time after 02)
--
-- Data source: reddit_db/csv_output/, generated by generate_data.py (Faker,
-- seed=42). No external datasets used.
-- =============================================================================

\echo '=== Loading data from csv_output/ ==='

-- \COPY runs on the client, so paths are relative to where psql was started.
-- Assumes psql is launched from the project root. If not, adjust the paths
-- or set: \cd /absolute/path/to/group_1_db_erd_phase_3

BEGIN;

-- -----------------------------------------------------------------------------
-- Order matters: respect FK dependencies.
--   user -> group -> follow, moderator, post -> comment -> vote
--   tag -> post_tag
--   report, notification last (they reference almost everything)
-- -----------------------------------------------------------------------------

\echo '-> user (2100)'
\COPY "user" (id, username, email, password_hash, avatar_url, karma, created_at) \
  FROM 'reddit_db/csv_output/user.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> group (1050)'
\COPY "group" (id, created_by, name, description, banner_url, member_count, is_nsfw, created_at) \
  FROM 'reddit_db/csv_output/group.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> follow (6300)'
\COPY follow (user_id, subreddit_id, subscribed_at) \
  FROM 'reddit_db/csv_output/follow.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> moderator (~1050)'
\COPY moderator (user_id, subreddit_id, permissions, added_at) \
  FROM 'reddit_db/csv_output/moderator.csv' WITH (FORMAT csv, HEADER true, NULL '');

-- post.csv column header is "post_type"; our column is "type". COPY matches
-- positionally when a column list is given, so the header name is irrelevant.
\echo '-> post (7500)'
\COPY post (id, author_id, subreddit_id, type, title, body, url, score, comment_count, is_archived, created_at) \
  FROM 'reddit_db/csv_output/post.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> comment (22000)'
\COPY comment (id, post_id, author_id, parent_comment_id, body, score, is_archived, created_at) \
  FROM 'reddit_db/csv_output/comment.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> vote (26500)'
\COPY vote (id, user_id, target_id, target_type, value, created_at) \
  FROM 'reddit_db/csv_output/vote.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> tag (1500)'
\COPY tag (id, subreddit_id, text, color) \
  FROM 'reddit_db/csv_output/tag.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> post_tag (4200)'
\COPY post_tag (post_id, tag_id, assigned_at) \
  FROM 'reddit_db/csv_output/post_tag.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> report (1250)'
\COPY report (id, reporter_id, resolved_by, target_id, target_type, reason, status, created_at, resolved_at) \
  FROM 'reddit_db/csv_output/report.csv' WITH (FORMAT csv, HEADER true, NULL '');

\echo '-> notification (13000)'
\COPY notification (id, user_id, actor_id, target_id, type, target_type, is_read, created_at) \
  FROM 'reddit_db/csv_output/notification.csv' WITH (FORMAT csv, HEADER true, NULL '');

COMMIT;

-- =============================================================================
-- Backfill denormalized counters.
-- The generator writes zeros for score / comment_count / member_count because
-- those are derived values. We recompute them now from the source-of-truth
-- tables (vote, comment, follow) so that triggers installed in 04_advanced.sql
-- have a consistent starting point.
-- =============================================================================

\echo '=== Backfilling denormalized counters ==='

BEGIN;

-- post.score = sum of post-votes
UPDATE post p
   SET score = sub.s
  FROM (
        SELECT target_id, COALESCE(SUM(value), 0)::INT AS s
          FROM vote
         WHERE target_type = 'post'
      GROUP BY target_id
       ) sub
 WHERE p.id = sub.target_id;

-- comment.score = sum of comment-votes
UPDATE comment c
   SET score = sub.s
  FROM (
        SELECT target_id, COALESCE(SUM(value), 0)::INT AS s
          FROM vote
         WHERE target_type = 'comment'
      GROUP BY target_id
       ) sub
 WHERE c.id = sub.target_id;

-- post.comment_count = count of comments (all, including archived)
UPDATE post p
   SET comment_count = sub.n
  FROM (
        SELECT post_id, COUNT(*)::INT AS n
          FROM comment
      GROUP BY post_id
       ) sub
 WHERE p.id = sub.post_id;

-- group.member_count = count of followers
UPDATE "group" g
   SET member_count = sub.n
  FROM (
        SELECT subreddit_id, COUNT(*)::INT AS n
          FROM follow
      GROUP BY subreddit_id
       ) sub
 WHERE g.id = sub.subreddit_id;

COMMIT;

-- =============================================================================
-- Sanity report
-- =============================================================================
\echo '=== Row counts ==='
SELECT 'user'         AS table_name, COUNT(*) FROM "user"
UNION ALL SELECT 'group',         COUNT(*) FROM "group"
UNION ALL SELECT 'follow',        COUNT(*) FROM follow
UNION ALL SELECT 'moderator',     COUNT(*) FROM moderator
UNION ALL SELECT 'post',          COUNT(*) FROM post
UNION ALL SELECT 'comment',       COUNT(*) FROM comment
UNION ALL SELECT 'vote',          COUNT(*) FROM vote
UNION ALL SELECT 'tag',           COUNT(*) FROM tag
UNION ALL SELECT 'post_tag',      COUNT(*) FROM post_tag
UNION ALL SELECT 'report',        COUNT(*) FROM report
UNION ALL SELECT 'notification',  COUNT(*) FROM notification
ORDER BY table_name;

-- Run ANALYZE so the planner has fresh statistics before anyone benchmarks
-- the indexes created in 01_ddl.sql.
ANALYZE;
